spring:
  application:
    name: DataAgent-server
  ai:
    dashscope:
      api-key: sk-29698f6bcc3a4b2f8f7a104b6c99baf0
  datasource:
    url: jdbc:mysql://localhost:3306/meeting
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
