spring:
  application:
    name: DataAgent-server
  ai:
    dashscope:
      api-key: sk-5ae98efc18c04c57af84daa48ac9ad95
  datasource:
    url: jdbc:mysql://localhost:3306/meeting
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
